version: '3.8'

services:
  tcp.server:
    init: true
    build:
      context: .
      dockerfile: src/docker/raw.server.dockerfile
    ports:
      - "4443:4443"
    environment:
      - host=:4443
    networks:
      - wsgo

  tcp.client:
    build:
      context: .
      dockerfile: src/docker/raw.client.dockerfile
    environment:
      - host=tcp.server:4443
    stdin_open: true 
    tty: true 
    networks:
      - wsgo
    depends_on:
      - tcp.server

  ws.server:
    build:
      context: .
      dockerfile: src/docker/ws.server.dockerfile
    ports:
      - "6443:6443"
    environment:
      - host=:6443
    networks:
      - wsgo

  ws.client:
    build:
      context: .
      dockerfile: src/docker/ws.client.dockerfile
    ports:
      - "6443:6443"
    environment:
      - host=ws.server:6443
    stdin_open: true 
    tty: true
    networks:
      - wsgo
    depends_on:
      - ws.server    

networks:
  wsgo:
    driver: bridge