version: "3.8"

services:
  tcp.server:
    init: true
    build:
      context: .
      dockerfile: ./raw.server.dockerfile
    ports:
      - "4443:4443"
    environment:
      - host=:4443
    networks:
      - wsgo

  ws.server:
    build:
      context: .
      dockerfile: ./ws.server.dockerfile
    ports:
      - "6443:6443"
    environment:
      - host=:6443
    networks:
      - wsgo

  p2p.server:
    build:
      context: .
      dockerfile: ./p2p.server.dockerfile
    ports:
      - "8443:8443"
    environment:
      - host=:8443
      - peers=:4443
    networks:
      - wsgo

networks:
  wsgo:
    driver: bridge
