version: '3.8'

services:
  tcp.server:
    init: true
    build:
      context: .
      dockerfile: src/docker/raw.server.dockerfile
    ports:
      - "4443:4443"
    environment:
      - host=:4443
    networks:
      - wsgo

  ws.server:
    build:
      context: .
      dockerfile: src/docker/ws.server.dockerfile
    ports:
      - "6443:6443"
    environment:
      - host=:6443
    networks:
      - wsgo   

networks:
  wsgo:
    driver: bridge